const STORE = {
  landlord: {
    active: [
      {
        id: 1,
        address: '86872 Jacob Gateway, Durganport, WV 48044',
        montly_rent: 3000,
        maintanance: 100,
        type_property: 'aparment',
        price: 5000,
        bedrooms: 2,
        bathrooms: 4,
        area: 180,
        pets: true,
        description: `3 Bedroom /2 Bathroom apartment available for ASAP move-in! Apartment features hardwood floors throughout`,
        picture: '',
      },
      {
        id: 2,
        address: '610 Zieme Ways, Lake Corey, AR 40537-6065',
        montly_rent: 2000,
        maintanance: 100,
        type_property: 'house',
        price: 5500,
        bedrooms: 4,
        bathrooms: 2,
        area: 180,
        pets: false,
        description: `3 Bedroom /2 Bathroom apartment available for ASAP move-in! Apartment features hardwood floors throughout`,
        picture: '',
      },
      {
        id: 3,
        address: 'Apt. 325 29166 Wuckert Heights, Adamland, MT 17471',
        montly_rent: 4000,
        maintanance: 100,
        type_property: 'aparment',
        price: 5300,
        bedrooms: 3,
        bathrooms: 5,
        area: 180,
        pets: true,
        description: `3 Bedroom /2 Bathroom apartment available for ASAP move-in! Apartment features hardwood floors throughout`,
        picture: '',
      },
    ],
    closed: [],
  },
};

export default STORE;
